var annotated_dup =
[
    [ "api", null, [
      [ "Status", "classapi_1_1_status.html", "classapi_1_1_status" ]
    ] ],
    [ "hermes", null, [
      [ "adapter", "namespacehermes_1_1adapter.html", "namespacehermes_1_1adapter" ],
      [ "api", null, [
        [ "BlobInfo", "structhermes_1_1api_1_1_blob_info.html", "structhermes_1_1api_1_1_blob_info" ],
        [ "Bucket", "classhermes_1_1api_1_1_bucket.html", "classhermes_1_1api_1_1_bucket" ],
        [ "Context", "structhermes_1_1api_1_1_context.html", "structhermes_1_1api_1_1_context" ],
        [ "Hermes", "classhermes_1_1api_1_1_hermes.html", "classhermes_1_1api_1_1_hermes" ],
        [ "ID", "classhermes_1_1api_1_1_i_d.html", "classhermes_1_1api_1_1_i_d" ],
        [ "PersistTrait", "structhermes_1_1api_1_1_persist_trait.html", "structhermes_1_1api_1_1_persist_trait" ],
        [ "Trait", "structhermes_1_1api_1_1_trait.html", "structhermes_1_1api_1_1_trait" ],
        [ "VBucket", "classhermes_1_1api_1_1_v_bucket.html", "classhermes_1_1api_1_1_v_bucket" ]
      ] ],
      [ "testing", null, [
        [ "TargetViewState", "structhermes_1_1testing_1_1_target_view_state.html", "structhermes_1_1testing_1_1_target_view_state" ]
      ] ],
      [ "Arena", "structhermes_1_1_arena.html", "structhermes_1_1_arena" ],
      [ "ArenaInfo", "structhermes_1_1_arena_info.html", "structhermes_1_1_arena_info" ],
      [ "Blob", "structhermes_1_1_blob.html", "structhermes_1_1_blob" ],
      [ "BlobID", "unionhermes_1_1_blob_i_d.html", "unionhermes_1_1_blob_i_d" ],
      [ "BlobInfo", "structhermes_1_1_blob_info.html", "structhermes_1_1_blob_info" ],
      [ "BlobInfoMap", "structhermes_1_1_blob_info_map.html", "structhermes_1_1_blob_info_map" ],
      [ "BoArgs", "unionhermes_1_1_bo_args.html", "unionhermes_1_1_bo_args" ],
      [ "BoTask", "structhermes_1_1_bo_task.html", "structhermes_1_1_bo_task" ],
      [ "BucketID", "unionhermes_1_1_bucket_i_d.html", "unionhermes_1_1_bucket_i_d" ],
      [ "BucketInfo", "structhermes_1_1_bucket_info.html", "structhermes_1_1_bucket_info" ],
      [ "BufferHeader", "structhermes_1_1_buffer_header.html", "structhermes_1_1_buffer_header" ],
      [ "BufferID", "unionhermes_1_1_buffer_i_d.html", "unionhermes_1_1_buffer_i_d" ],
      [ "BufferIdArray", "structhermes_1_1_buffer_id_array.html", "structhermes_1_1_buffer_id_array" ],
      [ "BufferIdHash", "structhermes_1_1_buffer_id_hash.html", "structhermes_1_1_buffer_id_hash" ],
      [ "BufferInfo", "structhermes_1_1_buffer_info.html", "structhermes_1_1_buffer_info" ],
      [ "BufferOrganizer", "structhermes_1_1_buffer_organizer.html", "structhermes_1_1_buffer_organizer" ],
      [ "BufferPool", "structhermes_1_1_buffer_pool.html", "structhermes_1_1_buffer_pool" ],
      [ "ChunkedIdList", "structhermes_1_1_chunked_id_list.html", "structhermes_1_1_chunked_id_list" ],
      [ "ClientRpcContext", "structhermes_1_1_client_rpc_context.html", "structhermes_1_1_client_rpc_context" ],
      [ "ClientThalliumState", "structhermes_1_1_client_thallium_state.html", "structhermes_1_1_client_thallium_state" ],
      [ "CommunicationContext", "structhermes_1_1_communication_context.html", "structhermes_1_1_communication_context" ],
      [ "Config", "structhermes_1_1_config.html", "structhermes_1_1_config" ],
      [ "DebugHeapAllocation", "structhermes_1_1_debug_heap_allocation.html", "structhermes_1_1_debug_heap_allocation" ],
      [ "DebugState", "structhermes_1_1_debug_state.html", "structhermes_1_1_debug_state" ],
      [ "Device", "structhermes_1_1_device.html", "structhermes_1_1_device" ],
      [ "EntireFile", "structhermes_1_1_entire_file.html", "structhermes_1_1_entire_file" ],
      [ "FreeBlock", "structhermes_1_1_free_block.html", "structhermes_1_1_free_block" ],
      [ "FreeBlockHeader", "structhermes_1_1_free_block_header.html", "structhermes_1_1_free_block_header" ],
      [ "Heap", "structhermes_1_1_heap.html", "structhermes_1_1_heap" ],
      [ "IdList", "structhermes_1_1_id_list.html", "structhermes_1_1_id_list" ],
      [ "IdMap", "structhermes_1_1_id_map.html", "structhermes_1_1_id_map" ],
      [ "MetadataManager", "structhermes_1_1_metadata_manager.html", "structhermes_1_1_metadata_manager" ],
      [ "MPIState", "structhermes_1_1_m_p_i_state.html", "structhermes_1_1_m_p_i_state" ],
      [ "RoundRobinState", "classhermes_1_1_round_robin_state.html", "classhermes_1_1_round_robin_state" ],
      [ "RpcContext", "structhermes_1_1_rpc_context.html", "structhermes_1_1_rpc_context" ],
      [ "ScopedTemporaryMemory", "structhermes_1_1_scoped_temporary_memory.html", "structhermes_1_1_scoped_temporary_memory" ],
      [ "SharedMemoryContext", "structhermes_1_1_shared_memory_context.html", "structhermes_1_1_shared_memory_context" ],
      [ "ShmemClientInfo", "structhermes_1_1_shmem_client_info.html", "structhermes_1_1_shmem_client_info" ],
      [ "Stats", "structhermes_1_1_stats.html", "structhermes_1_1_stats" ],
      [ "SwapBlob", "structhermes_1_1_swap_blob.html", "structhermes_1_1_swap_blob" ],
      [ "SystemViewState", "structhermes_1_1_system_view_state.html", "structhermes_1_1_system_view_state" ],
      [ "Target", "structhermes_1_1_target.html", "structhermes_1_1_target" ],
      [ "TargetID", "unionhermes_1_1_target_i_d.html", "unionhermes_1_1_target_i_d" ],
      [ "TargetInfo", "structhermes_1_1_target_info.html", "structhermes_1_1_target_info" ],
      [ "TemporaryMemory", "structhermes_1_1_temporary_memory.html", "structhermes_1_1_temporary_memory" ],
      [ "ThalliumState", "structhermes_1_1_thallium_state.html", "structhermes_1_1_thallium_state" ],
      [ "ThreadPool", "classhermes_1_1_thread_pool.html", "classhermes_1_1_thread_pool" ],
      [ "Ticket", "structhermes_1_1_ticket.html", "structhermes_1_1_ticket" ],
      [ "TicketMutex", "structhermes_1_1_ticket_mutex.html", "structhermes_1_1_ticket_mutex" ],
      [ "Token", "structhermes_1_1_token.html", "structhermes_1_1_token" ],
      [ "TokenList", "structhermes_1_1_token_list.html", "structhermes_1_1_token_list" ],
      [ "TraitIdArray", "structhermes_1_1_trait_id_array.html", "structhermes_1_1_trait_id_array" ],
      [ "VBucketID", "unionhermes_1_1_v_bucket_i_d.html", "unionhermes_1_1_v_bucket_i_d" ],
      [ "VBucketInfo", "structhermes_1_1_v_bucket_info.html", "structhermes_1_1_v_bucket_info" ]
    ] ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "HeapMetadata", "struct_heap_metadata.html", "struct_heap_metadata" ],
    [ "Point", "struct_point.html", "struct_point" ],
    [ "Range", "struct_range.html", "struct_range" ],
    [ "stbds_array_header", "structstbds__array__header.html", "structstbds__array__header" ],
    [ "stbds_string_arena", "structstbds__string__arena.html", "structstbds__string__arena" ],
    [ "stbds_string_block", "structstbds__string__block.html", "structstbds__string__block" ],
    [ "WindowData", "struct_window_data.html", "struct_window_data" ]
];